 GET http://localhost:3000/getJson

# POST http://localhost:3000/post
# Content-Type: application/json

# {   
    
#    "author": "Ivy",
#    "title": "Spotlight yeah",
#    "body": "Racheal is a political science graduate",
#    "comments": {
#             "name": "Suzzy",
#             "message": "good soul"
#            }  
  
# }

